server:
  port: 7081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/products_catalog
    username: postgres
    password: "Qhawe&Khanyisa_"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true


