name: CI -  E-commerce management

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Automatically caches dependencies to speed up future runs

      - name: Run tests
        run: mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: target/surefire-reports/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Reuses the cached dependencies from the test job

      - name: Build and Package Application
        run: mvn clean package -DskipTests # Packages code into an executable JAR, skipping tests since they ran in the previous job

      - name: Upload Executable JAR Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ecommerce-application-jar
          path: target/*.jar
