spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

        - id: seller-service
          uri: http://localhost:8084
          predicates:
            - Path=/seller/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

        - id: review-service
          uri: http://localhost:8087
          predicates:
            - Path=/review/**
          filters:
            - StripPrefix=1

        - id: address-service
          uri: http://localhost:8088
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1

        - id: customer-service
          uri: http://localhost:8089
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix

        - id: catalog-service
          uri: http://localhost:8090
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1




